Switch to yarn v4
Jahia/jcontent pull request #1225
Opened 2024-06-06 20:40 UTC by gflores-jahia

## JIRA

https://jira.jahia.org/browse/PROJECT-XXX

## Description

## Tests

The following are included in this PR
- [ ] Unit Tests (Most changes _should_ have unit tests)
- [ ] Integration Tests

## Checklist

I have considered the following implications of my change: 

- [ ] Security (in particular for changes to authentication, authorization, data fetching, ...)
- [ ] Performance
- [ ] Migration
- [ ] Code maintainability

## Documentation

- [ ] Inline documentation
- [ ] Internal Documentation (wiki)
- [ ] User-facing Documentation

2024-06-06 20:46 UTC, cedmail commented
@gflores-jahia maybe it should be a draft for now?

2024-06-06 20:46 UTC, cedmail requested changes
Linting, compiling issues

2024-06-06 20:47 UTC, gflores-jahia commented
@cedmail yes indeed, sorry I forgot it auto-assigns the reviewers

2024-11-07 19:33 UTC, gflores-jahia commented
Modify resolutions and upgrade schema-utils which is what's requiring old (vulnerable) ajv package https://github.com/advisories/GHSA-v88g-cgmw-v5xw

```
> yarn why ajv
├─ schema-utils@npm:0.3.0
│  └─ ajv@npm:5.5.2 (via npm:^5.0.0)
```

Also resolution can be set on yarn.lock using:

`yarn set resolution schema-utils@npm:^0.3.0 npm:1.0.0` (take note of npm qualifier otherwise it throws `Error: ajv@6.12.6 isn't supported by any available resolver`)

2026-01-28 13:23 UTC, closed without merging