BACKLOG-20529 Allow header to shrink
Jahia/jcontent pull request #742
Opened 2023-04-04 15:26 UTC by AKarmanov

## JIRA

https://jira.jahia.org/browse/BACKLOG-20529

## Description

Allow header to shrink. Changes in CE and PC have already ben merged in. We were waiting for release of jContent to merge these changes.

2023-04-04 15:34 UTC, tdraier approved these changes

2023-04-04 15:53 UTC, tdraier commented
After discussion with felix, the MenuLabelActionComponent should actually be in moonstone - it should be a `MenuItem variant="title"`

2023-04-04 15:54 UTC, tdraier requested changes
Use a MenuItem instead of a custom MenuLabelComponent

2023-04-06 09:43 UTC, tdraier commented
moonstone upgraded, included some feedbacks from @ffffffelix regarding layouts and buttons

2023-04-06 09:44 UTC, tdraier approved these changes, later dismissed

2023-04-06 09:48 UTC, tdraier approved these changes

2023-04-06 13:07 UTC, gflores-jahia approved these changes

2023-04-06 13:08 UTC, merged